### PR TITLE
580 Implement new retry logic for transfers and max flow

### LINKED ISSUE #540: Max amount between shared wallets displaying wrong max flow value
**Describe the bug**

A shared wallet wanting to send CRC to another SW, the max flow amount is displayed incorrectly

**To Reproduce**
1. Go to a shared wallet profile
2. Click on  send circles
3. wait until max amount is displayed 

**Expected behavior**
The max flow amount in time circles

**Screenshots**

Screenshot 2022-11-21 at 18 56 21

**Additional context**
Use this query to check the value returned from the API, this comes in Circles ( so a conversion is needed to time circles)

`{"from":"0x3c89A829400Ea3B49F25738A1F4015A7961D0301","to":"0x9BA1Bcd88E99d6E1E03252A70A63FEa83Bf1208c","value":"1000000000000000000000000000000000"}`

response 
```
{
	"status": "ok",
	"data": {
		"from": "0x3c89A829400Ea3B49F25738A1F4015A7961D0301",
		"to": "0x9BA1Bcd88E99d6E1E03252A70A63FEa83Bf1208c",
		"maxFlowValue": "29100587751936619099862",
		"processDuration": 154335,
		"transferValue": "1000000000000000000000000000000000",
		"transferSteps": []
	}
}
```

### PR DESCRIPTION
**Pull request by louilinn**
- [x] finish core update https://github.com/CirclesUBI/circles-core/pull/153
- [x] add pathfinder hops default constant
- [x] update core service definitions
- [x] new transfer loop
- [x] loop for max flow
- [x] tested on prod data in complex web of trust between shared wallets in preview Netlify deployment
- [x] clean up

Resolves issue: https://github.com/CirclesUBI/circles-myxogastria/issues/580
Closes: https://github.com/CirclesUBI/circles-myxogastria/issues/540#issuecomment-1404436725

### CODE REVIEW

File: src/store/token/actions.js [hunk 1]
```diff
@@ -203,29 +208,168 @@ export function requestUBIPayout(payout) {
...
+  try {
+    console.log('Attempting with params ', {
+      from,
+      to,
+      value,
+      paymentNote,
+      hops,
+    });
+    return core.token.transfer(from, to, value, paymentNote, hops);
+  } catch (error) {
```
Comment (louilinn) [inline src/store/token/actions.js]: I don't seem to be able to catch the 504

Comment (llunaCreixent) [reply src/store/token/actions.js]: try now after changing the timeout in the api

**Comment by louilinn** [comment]
Example of successful max flow calculation is shared internally (sensitive business data). It was successful on second attempt with 2 hops between 2 shared wallets with complex connections. Max value is very big and expected to be of this approximate size.

File: src/utils/findPath.js [hunk 2]
```diff
@@ -1,5 +1,52 @@
 import core from '~/services/core';
 import web3 from '~/services/web3';
+import { PATHFINDER_HOPS_DEFAULT } from '~/utils/constants';
+
+const { ErrorCodes } = core.errors;
+const LARGE_AMOUNT = new web3.utils.BN(
+  web3.utils.toWei('1000000000000000', 'ether'),
```
Comment (mikozet) [inline src/utils/findPath.js:7]: why particularly this value 1000000000000000? maybe we could add comment?

Comment (mikozet) [inline src/utils/findPath.js:11]: why particularly this value 1000000000000000? maybe we could add comment?

File: src/store/token/actions.js [hunk 3]
```diff
@@ -203,29 +204,86 @@ export function requestUBIPayout(payout) {
...
+  to,
+  value,
+  paymentNote,
+  hops,
+  attemptsLeft,
+  errorsMessages = '',
+) {
+  if (attemptsLeft === 0 || hops === 0) {
+    // ran out of attempts or hops, cannot attempt further transfers
+    throw new TransferError(errorsMessages);
```
Comment (mikozet) [inline src/store/token/actions.js:219]: should we here display message for users?

File: src/store/token/actions.js (hunk 1 above)
Comment (mikozet) [reply src/store/token/actions.js]: what was the reason console.log hasn't been displayed? are they now?

File: src/store/token/actions.js [hunk 4]
```diff
@@ -203,29 +204,86 @@ export function requestUBIPayout(payout) {
...
+        errorsMessages.concat(' ', error.message),
+      );
+    }
+    // if the path is found but it is invalid
+    else if (
+      (error.name === 'TransferError' && ErrorCodes.TRANSFER_NOT_FOUND) || // search complete and no path found
+      error.name !== 'TransferError' // includes errors from attempting transfer with an invalid path
+    ) {
+      // update the edges db for trust-adjacent safes
+      await core.token.updateTransferSteps(from, to, value, hops);
```
Comment (mikozet) [inline src/store/token/actions.js]: shouldn't we have try catch here? Otherwise this query goes silent once there is error from it?

File: src/store/token/actions.js [hunk 5]
```diff
@@ -203,29 +204,86 @@ export function requestUBIPayout(payout) {
...
+    // ---
+    // no path or path too long
+    if (
+      error.name === 'TransferError' &&
+      (error.code === ErrorCodes.TOO_COMPLEX_TRANSFER || // too many steps in found path
+        error.code === ErrorCodes.UNKNOWN_ERROR || // includes timeout error from api
+        error.code === ErrorCodes.INVALID_TRANSFER) // other errors from find transitive transfer
+    ) {
+      // retry with fewer hops
+      return await loopTransfer(
```
Comment (mikozet) [inline src/store/token/actions.js:236]: maybe would be worth to update the edges of db here as well before looping again?

File: src/store/token/actions.js [hunk 6]
```diff
@@ -203,29 +204,86 @@ export function requestUBIPayout(payout) {
...
+        value,
+        paymentNote,
+        hops,
+        attemptsLeft - 1,
+        errorsMessages.concat(' ', error.message),
+      );
+    }
+    // any other errors will result in propagating the error
+    else {
+      throw error;
```
Comment (mikozet) [inline src/store/token/actions.js]: what about information for users? shouldn't we display a message for them?

File: src/store/token/actions.js (hunk 1 above)
Comment (louilinn) [reply src/store/token/actions.js]: Yes it changed to 422 but that is caught in core and core then throws new/other errors according to here: https://github.com/CirclesUBI/circles-core/blob/b661de206bbaaa3a8aca4cc289e0539c48a8600e/src/token.js#L562

File: src/store/token/actions.js (hunk 3 above)
Comment (louilinn) [reply src/store/token/actions.js:219]: This error is caught (i think in SendConfirm). I kept these as a debug log as the error will go in the logs. I will also add some kind of interpretation to the user here https://github.com/CirclesUBI/circles-myxogastria/blob/29599c9ae2e28ac7e1c0aaa961f641cc858a769e/src/views/SendConfirm.js#L137 Thanks!

File: src/store/token/actions.js (hunk 4 above)
Comment (louilinn) [reply src/store/token/actions.js]: Yes I thought about it.. but wasn't sure how to do it in a good why, what to do if it fails?

File: src/store/token/actions.js (hunk 5 above)
Comment (louilinn) [reply src/store/token/actions.js:236]: no because it will take more time, and there is no indication that edges are outdated, just that it is either too many hops or takes to long to calculate. most likely update edges will also time out due to the same reason. We use update when a found path is not accepted as transfer

File: src/utils/findPath.js (hunk 2 above)
Comment (louilinn) [reply src/utils/findPath.js:11]: I thought large amount as name was enough but I can add comment :)

File: src/store/token/actions.js (hunk 6 above)
Comment (louilinn) [reply src/store/token/actions.js]: This error is caught (i think in SendConfirm). I kept these as a debug log as the error will go in the logs. I will also add some kind of interpretation to the user here https://github.com/CirclesUBI/circles-myxogastria/blob/29599c9ae2e28ac7e1c0aaa961f641cc858a769e/src/views/SendConfirm.js#L137 Thanks!

File: src/store/token/actions.js (hunk 5 above)
Comment (louilinn) [reply src/store/token/actions.js:236]: https://github.com/CirclesUBI/circles-myxogastria/blob/29599c9ae2e28ac7e1c0aaa961f641cc858a769e/src/views/SendConfirm.js#L137

File: src/utils/findPath.js (hunk 2 above)
Comment (louilinn) [reply src/utils/findPath.js:11]: I will add something like "findTransitiveTransfer returns a maxFlow value when a too large amount is specified as amount. If the amount is in the order of magnitude of actual possible transfers it will return the steps of that transfer instead. We use 10¹⁵ CRC as this unrealistic amount."

File: src/store/token/actions.js (hunk 4 above)
Comment (mikozet) [reply src/store/token/actions.js]: I would log the error. We might think about notification as well so it is a clear point where the actual issue is once it happens..

**Comment by louilinn** [comment]
Try it out in preview :)

File: src/store/token/actions.js (hunk 3 above)
Comment (mikozet) [reply src/store/token/actions.js:219]: "I will also add some kind of interpretation to the user here"
Is it done somewhere, I do not see?

File: src/store/token/actions.js (hunk 4 above)
Comment (mikozet) [reply src/store/token/actions.js]: I do not see where we catch error from `core.token.updateTransferSteps`

File: src/store/token/actions.js (hunk 6 above)
Comment (mikozet) [reply src/store/token/actions.js]: Is interpretation for the user there?

**Review by mikozet — CHANGES_REQUESTED** [review]
still some comments haven't been addressed

File: src/store/token/actions.js (hunk 6 above)
Comment (louilinn) [reply src/store/token/actions.js]: Yes and it will be improved when working on the task to improve that view

File: src/store/token/actions.js [hunk 7]
```diff
@@ -203,29 +204,105 @@ export function requestUBIPayout(payout) {
...
+      // search complete and no path found
+      (transferError.name === 'TransferError' &&
+        ErrorCodes.TRANSFER_NOT_FOUND) ||
+      // includes errors from attempting transfer with an invalid path
+      transferError.name !== 'TransferError'
+    ) {
+      // update the edges db for trust-adjacent safes
+      try {
+        await core.token.updateTransferSteps(from, to, value, hops);
+      } catch (updateError) {
```
Comment (louilinn) [inline src/store/token/actions.js:257]: here the update error is caught? Is there something else to be done? @mikozet

File: src/store/token/actions.js (hunk 3 above)
Comment (louilinn) [reply src/store/token/actions.js:219]: Would it be ok to do this as part of the improve send confirm task?

File: src/store/token/actions.js (hunk 4 above)
Comment (louilinn) [reply src/store/token/actions.js]: I tagged you in a comment with the code

File: src/store/token/actions.js (hunk 3 above)
Comment (mikozet) [reply src/store/token/actions.js:219]: ok

**Review by mikozet — APPROVED** [review]
